name: Build REDUX 1.8 Web
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - name: Build Web Client
        run: |
          chmod +x gradlew
          ./gradlew build --no-daemon
          
      - name: Upload REDUX Game
        uses: actions/upload-artifact@v4
        with:
          name: REDUX-Playable-Game
          path: |
            target_teavm_javascript/javascript/
            target_teavm_wasm_gc/javascript/
            target_teavm_javascript/javascript_dist/
