name: Build REDUX 1.8 Web
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build Offline Client
        run: |
          chmod +x gradlew
          ./gradlew :target_teavm_javascript:makeOfflineDownload --no-daemon

      - name: Upload HTML Client
        uses: actions/upload-artifact@v4
        with:
          name: REDUX-Client
          path: |
            javascript/*.html
            target_teavm_javascript/build/teavm/dist/*.html
